name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:

  test:
    name: "Tests"
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 14.x

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-lint-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: npm install
      run: npm install
    - name: lint js
      run: node_modules/.bin/eslint . --ext=js,ts
    - name: test
      run: npm run test

  compat:
    name: Compatibility
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - ember-changeset

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 14.x
    - name: Install deps
      run: npm install
    - name: "Test: ${{ matrix.lib }}"
      run: npm run test-external:${{ matrix.lib }}

